config/routes.rb
Rails.application.routes.draw do
  resources :posts do  
  resources :comments
  end
  devise_for :users, :controllers => { registrations: 'registrations' }
  root "posts#index"
  get "about" => "pages#about"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :user
    has_attached_file :image, :styles => { :medium => "640x", :thumb => "100x100>" }
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
    has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :name
   devise_parameter_sanitizer.for(:account_update) << :name
 end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id
  
    if @comment.save
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    else
      flash[:alert] = "Revisa el formulario de comentarios, algo salió mal :/"
      render root_path
    end
  end


  def destroy  
    @comment = @post.comments.find(params[:id])
    if @comment.user_id == current_user.id
     @comment.delete
     respond_to do |format|
       format.html { redirect_to root_path }
       format.js
     end
    end
  end

  private

  def comment_params  
    params.require(:comment).permit(:content)
  end

  def set_post  
    @post = Post.find(params[:post_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :owned_post, only: [:edit, :update, :destroy]
  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = current_user.posts.build
  end

  def edit
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to @post, notice: '¡Post creado satisfactoriamente!'
    else
      render :new
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: '¡Post actualizado satisfactoriamente!'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find_by(id: params[:id])
    end

    def correct_user
      @post = current_user.posts.find_by(id: params[:id])
      redirect_to posts_path, notice: "¡No estás autorizada/o para editar este post!" if @post.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:description, :image)
    end
 private

  def owned_post  
    unless current_user == @post.user
      flash[:alert] = "¡Este post no te pertenece!"
      redirect_to root_path
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation, :current_password)
  end
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment" id="comment_<%= comment.id %>">
  <div class="user-name">
    <%= comment.user.name %>
  </div>
  <div class="comment-content">
    <%= comment.content %>
  </div>
  <% if comment.user == current_user %>
    <%= link_to post_comment_path(post, comment),  method: :delete, data: { confirm: "¿Estás segura?" }, remote: true  do %>
      <span class="glyphicon glyphicon-remove delete-comment"></span>
    <% end %>
  <% end %>
</div>

app/views/comments/create.js.erb
$('#comments_<%= @post.id %>').append("<%=j render 'comments/comment', post: @post, comment: @comment %>");
$('#comment_content_<%= @post.id %>').val('')

app/views/comments/destroy.js.erb
$('#comments_<%= @post.id %>').html("<%= j render @post.comments, post: @post, comment: @comment %>");

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
         <%= link_to "Instagram", root_path, class: "navbar-brand" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
            <% if user_signed_in? %>
                  <li><%= link_to 'Nuevo post', new_post_path %></li>
                  <li><%= link_to "Mi cuenta", edit_user_registration_path %></li>   
                  <li><%= link_to current_user.name, "#" %></li>
                  <li><%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete %></li>
                    <% else %>
                    
                  <li><%= link_to "Iniciar sesión", new_user_session_path %></li>
            <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<%= link_to "Home", root_path %>
<%= link_to "About", about_path %>
<div class="container">
  <% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
  <% end %>
    <%= yield %>
</div>


</body>
</html>

app/views/pages/about.html.erb
<h1>¿Quiénes somos?</h1>
<p>Estamos trabajando en nuestra aplicación Instagram</p>

app/views/pages/home.html.erb
<div class="jumbotron text-center">
  <h1>¡Bienvenidos a mi aplicación!</h1>
  <p>
    <%= link_to "Iniciar sesión", new_user_session_path, class: "btn btn-default btn-lg" %>
    <%= link_to "Regístrate", new_user_registration_path, class: "btn btn-primary btn-lg" %>
  </p>    
</div>

app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-head">
      <div class="thumb-img"></div>
      <div class="user-name">
        <%= post.user.name %>
      </div>
    </div>
    <div class="image center-block">
      <%= link_to (image_tag post.image.url(:medium), class:'img-responsive'), post_path(post) %>
    </div>
    <div class="post-bottom">
      <div class="description">
        <div class="user-name">
          <%= post.user.name %>
        </div>
        <%= post.description %>
      </div>
     <div class="comments" id="comments_<%= post.id %>">
      <% if post.comments %>
        <%= render post.comments, post: post %>
      <% end %>
    </div>
    </div>
    <div class="comment-like-form row">
      <div class="like-button col-sm-1">
        <span class="glyphicon glyphicon-heart-empty"></span>
      </div>
      <div class="comment-form col-sm-11">
        <%= form_for([post, post.comments.build], remote: true) do |f| %>
        <%= f.text_field :content, placeholder: 'Añade un comentario...', id: "comment_content_#{post.id}" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="form-wrapper">
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <%= render 'post', post: post %>
<% end %>

app/views/posts/new.html.erb
<div class="form-wrapper">
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
<%= render 'post', post: @post %>
<% if @post.user.id == current_user.id %>
  <div class="text-center edit-links">
    <%= link_to "Cancelar", posts_path %>
    |
    <%= link_to "Editar el post", edit_post_path(@post) %>
  </div>
<% else %>
  <div class="text-center edit-links">
    <%= link_to "Cancelar", posts_path %>
  </div>
<% end %>